name: Revert

on: 
  release:
    types: [deleted]

jobs: 
  revert:
    name: Revert 
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Revert
        run: ./revert.sh ${{ github.event.release.name }} ${{ github.repository }}
